apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: fbansept/api_python_poc
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: flask-logs
              mountPath: /var/log/flask
      volumes:
        - name: flask-logs
          persistentVolumeClaim:
            claimName: flask-logs-pvc
